//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AICDebugHelper.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal loc() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AICDebugHelper.Localization.loc", typeof(loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Original option: allskill
        ///Enables all hidden skills. 的本地化字符串。
        /// </summary>
        public static string CBallskillTT {
            get {
                return ResourceManager.GetString("CBallskillTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mighty Attack 的本地化字符串。
        /// </summary>
        public static string CBmighty {
            get {
                return ResourceManager.GetString("CBmighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original option: mighty
        ///One Punch Alchemist. 的本地化字符串。
        /// </summary>
        public static string CBmightyTT {
            get {
                return ResourceManager.GetString("CBmightyTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Settings 的本地化字符串。
        /// </summary>
        public static string CBnocfg {
            get {
                return ResourceManager.GetString("CBnocfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original option: nocfg
        ///Starts the game with default settings. 的本地化字符串。
        /// </summary>
        public static string CBnocfgTT {
            get {
                return ResourceManager.GetString("CBnocfgTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invincible 的本地化字符串。
        /// </summary>
        public static string CBnodamage {
            get {
                return ResourceManager.GetString("CBnodamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original option: nodamage
        ///Always receive 0 dmg. Will go crazy with vines. 的本地化字符串。
        /// </summary>
        public static string CBnodamageTT {
            get {
                return ResourceManager.GetString("CBnodamageTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Sound 的本地化字符串。
        /// </summary>
        public static string CBnosnd {
            get {
                return ResourceManager.GetString("CBnosnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original option: nosnd
        ///Denies loading sound resources. Can reduce loading time.
        ///Doesn&apos;t seem to work tho. 的本地化字符串。
        /// </summary>
        public static string CBnosndTT {
            get {
                return ResourceManager.GetString("CBnosndTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload Scripts 的本地化字符串。
        /// </summary>
        public static string CBreloadmtr {
            get {
                return ResourceManager.GetString("CBreloadmtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original option: reloadmtr
        ///Enables reloading which allows you to use F9 in game to reload all StreamingAssets/localization/**.txt scripts. 的本地化字符串。
        /// </summary>
        public static string CBreloadmtrTT {
            get {
                return ResourceManager.GetString("CBreloadmtrTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Super Cyclone Glitch 的本地化字符串。
        /// </summary>
        public static string CBsupercyclone {
            get {
                return ResourceManager.GetString("CBsupercyclone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original option: supercyclone
        ///Anti-Gravity. 的本地化字符串。
        /// </summary>
        public static string CBsupercycloneTT {
            get {
                return ResourceManager.GetString("CBsupercycloneTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weak Noel 的本地化字符串。
        /// </summary>
        public static string CBweak {
            get {
                return ResourceManager.GetString("CBweak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original option: weak
        ///Now I&apos;ve seen everything. 的本地化字符串。
        /// </summary>
        public static string CBweakTT {
            get {
                return ResourceManager.GetString("CBweakTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable All Skills 的本地化字符串。
        /// </summary>
        public static string CGallskill {
            get {
                return ResourceManager.GetString("CGallskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug? 的本地化字符串。
        /// </summary>
        public static string CheckBoxUseDebug {
            get {
                return ResourceManager.GetString("CheckBoxUseDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;User canceled or an error occured.&gt; 的本地化字符串。
        /// </summary>
        public static string DirBoxError {
            get {
                return ResourceManager.GetString("DirBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can also manually input a directory here. 的本地化字符串。
        /// </summary>
        public static string dirBoxTT {
            get {
                return ResourceManager.GetString("dirBoxTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AiC Directory Found. 的本地化字符串。
        /// </summary>
        public static string DirFound {
            get {
                return ResourceManager.GetString("DirFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can drag here to move the window. 的本地化字符串。
        /// </summary>
        public static string DragToMove {
            get {
                return ResourceManager.GetString("DragToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select game executable above. 的本地化字符串。
        /// </summary>
        public static string initStartupTest {
            get {
                return ResourceManager.GetString("initStartupTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select executable or enter directory: 的本地化字符串。
        /// </summary>
        public static string InputDirectory {
            get {
                return ResourceManager.GetString("InputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改程序语言。 的本地化字符串。
        /// </summary>
        public static string LanguageBoxTT {
            get {
                return ResourceManager.GetString("LanguageBoxTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target directory doesn&apos;t seem to be a valid AiC directory.... 的本地化字符串。
        /// </summary>
        public static string NotAICDir {
            get {
                return ResourceManager.GetString("NotAICDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re reading a random text file, stuff&apos;s not going to work. 的本地化字符串。
        /// </summary>
        public static string ReadingRandom {
            get {
                return ResourceManager.GetString("ReadingRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save the file in specified path (Overwrite). 的本地化字符串。
        /// </summary>
        public static string SaveButtonTT {
            get {
                return ResourceManager.GetString("SaveButtonTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Saved! 的本地化字符串。
        /// </summary>
        public static string SavedLabel {
            get {
                return ResourceManager.GetString("SavedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR 的本地化字符串。
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Failed. 的本地化字符串。
        /// </summary>
        public static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EZ Mode 的本地化字符串。
        /// </summary>
        public static string tabOneHeader {
            get {
                return ResourceManager.GetString("tabOneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Reader 的本地化字符串。
        /// </summary>
        public static string tabTwoHeader {
            get {
                return ResourceManager.GetString("tabTwoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original option: &lt;DEBUG&gt;
        ///Allows debugging and enables the checkboxes below. 的本地化字符串。
        /// </summary>
        public static string UseDebugTT {
            get {
                return ResourceManager.GetString("UseDebugTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It&apos;s not how it works, mate. 的本地化字符串。
        /// </summary>
        public static string UserInputError {
            get {
                return ResourceManager.GetString("UserInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string WndCtrClose {
            get {
                return ResourceManager.GetString("WndCtrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit the application. 的本地化字符串。
        /// </summary>
        public static string WndCtrCloseTT {
            get {
                return ResourceManager.GetString("WndCtrCloseTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize
        ///Restore 的本地化字符串。
        /// </summary>
        public static string WndCtrMaxRestore {
            get {
                return ResourceManager.GetString("WndCtrMaxRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize or Restore the window. 的本地化字符串。
        /// </summary>
        public static string WndCtrMaxRestoreTT {
            get {
                return ResourceManager.GetString("WndCtrMaxRestoreTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        public static string WndCtrMinimize {
            get {
                return ResourceManager.GetString("WndCtrMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize the window. 的本地化字符串。
        /// </summary>
        public static string WndCtrMinimizeTT {
            get {
                return ResourceManager.GetString("WndCtrMinimizeTT", resourceCulture);
            }
        }
    }
}
